.

diff --git a/bin/attempt b/bin/attempt
--- a/bin/attempt
+++ b/bin/attempt
@@ -6,20 +6,17 @@ colors
 success="$fg_bold[green]✓$reset_color"
 failure="$fg_bold[red]✗$reset_color"
 
-if result=$("$@" 2>&1)
-then
-	echo -n "$success"
-	clean_exit=1
-else
-	echo -n "$failure"
-fi
+result=$("$@" 2>&1)
+exitcode = $?
+
+(( $exitcode )) && (echo -n "$success") || (echo -n "$failure")
+
 echo "  \"$@\""
 
 if [[ -n $result ]]
 then
 	echo -n "     "
-	(( $clean_exit )) && echo -n "$fg[green]" || echo -n "$fg[red]"
+	(( $exitcode )) && echo -n "$fg[green]" || echo -n "$fg[red]"
 	echo "$result"
+	echo -n "$reset_color"
 fi
-
-echo -n "$reset_color"
