.

diff --git a/bin/attempt b/bin/attempt
--- a/bin/attempt
+++ b/bin/attempt
@@ -7,16 +7,16 @@ success="$fg_bold[green]✓$reset_color"
 failure="$fg_bold[red]✗$reset_color"
 
 result=$("$@" 2>&1)
-exitcode = $?
+exitcode=$?
 
-(( $exitcode )) && (echo -n "$success") || (echo -n "$failure")
+(( $exitcode )) && (echo -n "$failure") || (echo -n "$success")
 
 echo "  \"$@\""
 
 if [[ -n $result ]]
 then
 	echo -n "     "
-	(( $exitcode )) && echo -n "$fg[green]" || echo -n "$fg[red]"
+	(( $exitcode )) && echo -n "$fg[red]" || echo -n "$fg[green]"
 	echo "$result"
 	echo -n "$reset_color"
 fi
